time:
  measurement:
    aspect:
      enabled: true

spring:
  mongodb:
    embedded:
      version: 4.4.11
  data:
    mongodb:
      database: libraryDB

mongock:
  change-logs-scan-package:
    - ru.otus.mongock.changelog

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG