time:
  measurement:
    aspect:
      enabled: true

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 5
  datasource:
    url: jdbc:postgresql://localhost:5430/libraryDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  main:
    allow-circular-references: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG